# Generated by Django 3.0.1 on 2019-12-24 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('address_book', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='addressAdmin',
            new_name='addressModel',
        ),
    ]
